set(CMAKE_VERBOSE_MAKEFILE TRUE)

message(STATUS "${PROJECT_NAME}: BUILD_TIME                     = '${BUILD_TIME}'")
message(STATUS "${PROJECT_NAME}: GIT_COMMIT_COUNT               = '${GIT_COMMIT_COUNT}'")
message(STATUS "${PROJECT_NAME}: version_major                  = '${version_major}'")
message(STATUS "${PROJECT_NAME}: version_minor                  = '${version_minor}'")
message(STATUS "${PROJECT_NAME}: version_patch                  = '${version_patch}'")
message(STATUS "${PROJECT_NAME}: PROJECT_VERSION                = '${PROJECT_VERSION}'")
message(STATUS "${PROJECT_NAME}: CMAKE_GENERATOR                = '${CMAKE_GENERATOR}'")
message(STATUS "${PROJECT_NAME}: CMAKE_GENERATOR_PLATFORM       = '${CMAKE_GENERATOR_PLATFORM}'")
message(STATUS "${PROJECT_NAME}: CMAKE_MAKE_PROGRAM             = '${CMAKE_MAKE_PROGRAM}'")
message(STATUS "${PROJECT_NAME}: CMAKE_SYSTEM_NAME              = '${CMAKE_SYSTEM_NAME}'")
message(STATUS "${PROJECT_NAME}: CMAKE_HOST_SYSTEM_NAME         = '${CMAKE_HOST_SYSTEM_NAME}'")
message(STATUS "${PROJECT_NAME}: CMAKE_PREFIX_PATH              = '${CMAKE_PREFIX_PATH}'")
message(STATUS "${PROJECT_NAME}: CMAKE_CXX_COMPILER             = '${CMAKE_CXX_COMPILER}'")
message(STATUS "${PROJECT_NAME}: CMAKE_CXX_COMPILER_ID          = '${CMAKE_CXX_COMPILER_ID}'")
message(STATUS "${PROJECT_NAME}: CMAKE_C_COMPILER               = '${CMAKE_C_COMPILER}'")
message(STATUS "${PROJECT_NAME}: CMAKE_BUILD_TYPE               = '${CMAKE_BUILD_TYPE}'")
message(STATUS "${PROJECT_NAME}: CMAKE_CURRENT_SOURCE_DIR       = '${CMAKE_CURRENT_SOURCE_DIR}'")
message(STATUS "${PROJECT_NAME}: CMAKE_CURRENT_BINARY_DIR       = '${CMAKE_CURRENT_BINARY_DIR}'")
message(STATUS "${PROJECT_NAME}: CMAKE_BINARY_DIR               = '${CMAKE_BINARY_DIR}'")
message(STATUS "${PROJECT_NAME}: CMAKE_RUNTIME_OUTPUT_DIRECTORY = '${CMAKE_RUNTIME_OUTPUT_DIRECTORY}'")
message(STATUS "${PROJECT_NAME}: CMAKE_CFG_INTDIR               = '${CMAKE_CFG_INTDIR}'")
message(STATUS "${PROJECT_NAME}: CMAKE_CXX_FLAGS                = '${CMAKE_CXX_FLAGS}' ")
